import credits.leo;

program distrofund_private_transfer_v2.aleo {
    struct Addresses1 {
        address1: address;
    }
    struct Addresses2 {
        address1: address;
        address2: address;
    }
    struct Addresses3 {
        address1: address;
        address2: address;
        address3: address;
    }
    struct Addresses4 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
    }
    struct Addresses5 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
    }
    struct Addresses6 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
    }
    struct Addresses7 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
    }
    struct Addresses8 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
        address8: address;
    }
    struct Addresses9 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
        address8: address;
        address9: address;
    }
    struct Addresses10 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
        address8: address;
        address9: address;
        address10: address;
    }
    struct Addresses11 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
        address8: address;
        address9: address;
        address10: address;
        address11: address;
    }
    struct Addresses12 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
        address8: address;
        address9: address;
        address10: address;
        address11: address;
        address12: address;
    }
    struct Addresses13 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
        address8: address;
        address9: address;
        address10: address;
        address11: address;
        address12: address;
        address13: address;
    }
    struct Addresses14 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
        address8: address;
        address9: address;
        address10: address;
        address11: address;
        address12: address;
        address13: address;
        address14: address;
    }
    struct Addresses15 {
        address1: address;
        address2: address;
        address3: address;
        address4: address;
        address5: address;
        address6: address;
        address7: address;
        address8: address;
        address9: address;
        address10: address;
        address11: address;
        address12: address;
        address13: address;
        address14: address;
        address15: address;
    }
    struct Amount1 {
        amount1: u64;
    }
    struct Amount2 {
        amount1: u64;
        amount2: u64;
    }
    struct Amount3 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
    }
    struct Amount4 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
    }
    struct Amount5 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
    }
    struct Amount6 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
    }
    struct Amount7 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
    }
    struct Amount8 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
        amount8: u64;
    }
    struct Amount9 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
        amount8: u64;
        amount9: u64;
    }
    struct Amount10 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
        amount8: u64;
        amount9: u64;
        amount10: u64;
    }
    struct Amount11 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
        amount8: u64;
        amount9: u64;
        amount10: u64;
        amount11: u64;
    }
    struct Amount12 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
        amount8: u64;
        amount9: u64;
        amount10: u64;
        amount11: u64;
        amount12: u64;
    }
    struct Amount13 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
        amount8: u64;
        amount9: u64;
        amount10: u64;
        amount11: u64;
        amount12: u64;
        amount13: u64;
    }
    struct Amount14 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
        amount8: u64;
        amount9: u64;
        amount10: u64;
        amount11: u64;
        amount12: u64;
        amount13: u64;
        amount14: u64;
    }
    struct Amount15 {
        amount1: u64;
        amount2: u64;
        amount3: u64;
        amount4: u64;
        amount5: u64;
        amount6: u64;
        amount7: u64;
        amount8: u64;
        amount9: u64;
        amount10: u64;
        amount11: u64;
        amount12: u64;
        amount13: u64;
        amount14: u64;
        amount15: u64;
    }

    transition transfer_one(sender_record: credits.leo/credits, receiver_address: Addresses1, amount: Amount1) -> (credits.leo/credits) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);

        return (sender_leftover_record);
    }

    transition transfer_two(sender_record: credits.leo/credits, receiver_address: Addresses2, amount: Amount2) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);

        return (sender_leftover_record1);
    }

    transition transfer_three(sender_record: credits.leo/credits, receiver_address: Addresses3, amount: Amount3) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);

        return (sender_leftover_record2);
    }

    transition transfer_four(sender_record: credits.leo/credits, receiver_address: Addresses4, amount: Amount4) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        
        return (sender_leftover_record3);
    }
    transition transfer_five(sender_record: credits.leo/credits, receiver_address: Addresses5, amount: Amount5) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        
        return (sender_leftover_record4);
    }

    transition transfer_six(sender_record: credits.leo/credits, receiver_address: Addresses6, amount: Amount6) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        
        return (sender_leftover_record5);
    }

    transition transfer_seven(sender_record: credits.leo/credits, receiver_address: Addresses7, amount: Amount7) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);

        return (sender_leftover_record6);
    }

    transition transfer_eight(sender_record: credits.leo/credits, receiver_address: Addresses8, amount: Amount8) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);
        let (receiver_record7, sender_leftover_record7): (credits, credits) = credits.leo/transfer_private(sender_leftover_record6, receiver_address.address8, amount.amount8);
        
        return (sender_leftover_record7);
    }

    transition transfer_nine(sender_record: credits.leo/credits, receiver_address: Addresses9, amount: Amount9) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);
        let (receiver_record7, sender_leftover_record7): (credits, credits) = credits.leo/transfer_private(sender_leftover_record6, receiver_address.address8, amount.amount8);
        let (receiver_record8, sender_leftover_record8): (credits, credits) = credits.leo/transfer_private(sender_leftover_record7, receiver_address.address9, amount.amount9);
        
        return (sender_leftover_record8);
    }

    transition transfer_ten(sender_record: credits.leo/credits, receiver_address: Addresses10, amount: Amount10) -> (
            credits.leo/credits
        ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);
        let (receiver_record7, sender_leftover_record7): (credits, credits) = credits.leo/transfer_private(sender_leftover_record6, receiver_address.address8, amount.amount8);
        let (receiver_record8, sender_leftover_record8): (credits, credits) = credits.leo/transfer_private(sender_leftover_record7, receiver_address.address9, amount.amount9);
        let (receiver_record9, sender_leftover_record9): (credits, credits) = credits.leo/transfer_private(sender_leftover_record8, receiver_address.address10, amount.amount10);
        
        return (sender_leftover_record9);
    }

    transition transfer_eleven(sender_record: credits.leo/credits, receiver_address: Addresses11, amount: Amount11) -> (
        credits.leo/credits
    ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);
        let (receiver_record7, sender_leftover_record7): (credits, credits) = credits.leo/transfer_private(sender_leftover_record6, receiver_address.address8, amount.amount8);
        let (receiver_record8, sender_leftover_record8): (credits, credits) = credits.leo/transfer_private(sender_leftover_record7, receiver_address.address9, amount.amount9);
        let (receiver_record9, sender_leftover_record9): (credits, credits) = credits.leo/transfer_private(sender_leftover_record8, receiver_address.address10, amount.amount10);
        let (receiver_record10, sender_leftover_record10): (credits, credits) = credits.leo/transfer_private(sender_leftover_record9, receiver_address.address11, amount.amount11);

        
        return (sender_leftover_record10);
    }

    transition transfer_twelve(sender_record: credits.leo/credits, receiver_address: Addresses12, amount: Amount12) -> (
        credits.leo/credits
    ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);
        let (receiver_record7, sender_leftover_record7): (credits, credits) = credits.leo/transfer_private(sender_leftover_record6, receiver_address.address8, amount.amount8);
        let (receiver_record8, sender_leftover_record8): (credits, credits) = credits.leo/transfer_private(sender_leftover_record7, receiver_address.address9, amount.amount9);
        let (receiver_record9, sender_leftover_record9): (credits, credits) = credits.leo/transfer_private(sender_leftover_record8, receiver_address.address10, amount.amount10);
        let (receiver_record10, sender_leftover_record10): (credits, credits) = credits.leo/transfer_private(sender_leftover_record9, receiver_address.address11, amount.amount11);
        let (receiver_record11, sender_leftover_record11): (credits, credits) = credits.leo/transfer_private(sender_leftover_record10, receiver_address.address12, amount.amount12);
       
        return (sender_leftover_record11);
    }

    transition transfer_thirteen(sender_record: credits.leo/credits, receiver_address: Addresses13, amount: Amount13) -> (
        credits.leo/credits
    ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);
        let (receiver_record7, sender_leftover_record7): (credits, credits) = credits.leo/transfer_private(sender_leftover_record6, receiver_address.address8, amount.amount8);
        let (receiver_record8, sender_leftover_record8): (credits, credits) = credits.leo/transfer_private(sender_leftover_record7, receiver_address.address9, amount.amount9);
        let (receiver_record9, sender_leftover_record9): (credits, credits) = credits.leo/transfer_private(sender_leftover_record8, receiver_address.address10, amount.amount10);
        let (receiver_record10, sender_leftover_record10): (credits, credits) = credits.leo/transfer_private(sender_leftover_record9, receiver_address.address11, amount.amount11);
        let (receiver_record11, sender_leftover_record11): (credits, credits) = credits.leo/transfer_private(sender_leftover_record10, receiver_address.address12, amount.amount12);
        let (receiver_record12, sender_leftover_record12): (credits, credits) = credits.leo/transfer_private(sender_leftover_record11, receiver_address.address13, amount.amount13);
   
        return (sender_leftover_record12);
    }

    transition transfer_fourteen(sender_record: credits.leo/credits, receiver_address: Addresses14, amount: Amount14) -> (
        credits.leo/credits
    ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);
        let (receiver_record7, sender_leftover_record7): (credits, credits) = credits.leo/transfer_private(sender_leftover_record6, receiver_address.address8, amount.amount8);
        let (receiver_record8, sender_leftover_record8): (credits, credits) = credits.leo/transfer_private(sender_leftover_record7, receiver_address.address9, amount.amount9);
        let (receiver_record9, sender_leftover_record9): (credits, credits) = credits.leo/transfer_private(sender_leftover_record8, receiver_address.address10, amount.amount10);
        let (receiver_record10, sender_leftover_record10): (credits, credits) = credits.leo/transfer_private(sender_leftover_record9, receiver_address.address11, amount.amount11);
        let (receiver_record11, sender_leftover_record11): (credits, credits) = credits.leo/transfer_private(sender_leftover_record10, receiver_address.address12, amount.amount12);
        let (receiver_record12, sender_leftover_record12): (credits, credits) = credits.leo/transfer_private(sender_leftover_record11, receiver_address.address13, amount.amount13);
        let (receiver_record13, sender_leftover_record13): (credits, credits) = credits.leo/transfer_private(sender_leftover_record12, receiver_address.address14, amount.amount14);
       
        return (sender_leftover_record13);
    }

    transition transfer_fifteen(sender_record: credits.leo/credits, receiver_address: Addresses15, amount: Amount15) -> (
        credits.leo/credits
    ) {
        let (receiver_record, sender_leftover_record): (credits, credits) = credits.leo/transfer_private(sender_record, receiver_address.address1, amount.amount1);
        let (receiver_record1, sender_leftover_record1): (credits, credits) = credits.leo/transfer_private(sender_leftover_record, receiver_address.address2, amount.amount2);
        let (receiver_record2, sender_leftover_record2): (credits, credits) = credits.leo/transfer_private(sender_leftover_record1, receiver_address.address3, amount.amount3);
        let (receiver_record3, sender_leftover_record3): (credits, credits) = credits.leo/transfer_private(sender_leftover_record2, receiver_address.address4, amount.amount4);
        let (receiver_record4, sender_leftover_record4): (credits, credits) = credits.leo/transfer_private(sender_leftover_record3, receiver_address.address5, amount.amount5);
        let (receiver_record5, sender_leftover_record5): (credits, credits) = credits.leo/transfer_private(sender_leftover_record4, receiver_address.address6, amount.amount6);
        let (receiver_record6, sender_leftover_record6): (credits, credits) = credits.leo/transfer_private(sender_leftover_record5, receiver_address.address7, amount.amount7);
        let (receiver_record7, sender_leftover_record7): (credits, credits) = credits.leo/transfer_private(sender_leftover_record6, receiver_address.address8, amount.amount8);
        let (receiver_record8, sender_leftover_record8): (credits, credits) = credits.leo/transfer_private(sender_leftover_record7, receiver_address.address9, amount.amount9);
        let (receiver_record9, sender_leftover_record9): (credits, credits) = credits.leo/transfer_private(sender_leftover_record8, receiver_address.address10, amount.amount10);
        let (receiver_record10, sender_leftover_record10): (credits, credits) = credits.leo/transfer_private(sender_leftover_record9, receiver_address.address11, amount.amount11);
        let (receiver_record11, sender_leftover_record11): (credits, credits) = credits.leo/transfer_private(sender_leftover_record10, receiver_address.address12, amount.amount12);
        let (receiver_record12, sender_leftover_record12): (credits, credits) = credits.leo/transfer_private(sender_leftover_record11, receiver_address.address13, amount.amount13);
        let (receiver_record13, sender_leftover_record13): (credits, credits) = credits.leo/transfer_private(sender_leftover_record12, receiver_address.address14, amount.amount14);
        let (receiver_record14, sender_leftover_record14): (credits, credits) = credits.leo/transfer_private(sender_leftover_record13, receiver_address.address15, amount.amount15);
     
        return (sender_leftover_record14);
    }
}
